-- V1__Create_Initial_Tables.sql

-- Tabela de Usuários
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    role VARCHAR2(20) NOT NULL,
    ativo NUMBER(1) DEFAULT 1,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Empresas
CREATE TABLE empresas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(200) NOT NULL,
    cnpj VARCHAR2(18) NOT NULL UNIQUE,
    setor VARCHAR2(100),
    endereco VARCHAR2(255),
    cidade VARCHAR2(100),
    estado VARCHAR2(2),
    contato VARCHAR2(100),
    email VARCHAR2(100),
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Equipamentos
CREATE TABLE equipamentos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id NUMBER NOT NULL,
    nome VARCHAR2(200) NOT NULL,
    tipo VARCHAR2(100) NOT NULL,
    potencia_watts NUMBER(10,2) NOT NULL,
    localizacao VARCHAR2(200),
    status VARCHAR2(20) DEFAULT 'ATIVO',
    data_instalacao DATE,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_equipamento_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id)
);

-- Tabela de Consumo de Energia
CREATE TABLE consumo_energia (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id NUMBER NOT NULL,
    equipamento_id NUMBER,
    data_leitura TIMESTAMP NOT NULL,
    consumo_kwh NUMBER(10,2) NOT NULL,
    custo_estimado NUMBER(10,2),
    periodo VARCHAR2(20),
    observacoes VARCHAR2(500),
    data_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_consumo_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_consumo_equipamento FOREIGN KEY (equipamento_id) REFERENCES equipamentos(id)
);

-- Tabela de Alertas
CREATE TABLE alertas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id NUMBER NOT NULL,
    equipamento_id NUMBER,
    tipo VARCHAR2(50) NOT NULL,
    severidade VARCHAR2(20) NOT NULL,
    mensagem VARCHAR2(500) NOT NULL,
    limite_excedido NUMBER(10,2),
    valor_atual NUMBER(10,2),
    status VARCHAR2(20) DEFAULT 'ATIVO',
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_resolucao TIMESTAMP,
    CONSTRAINT fk_alerta_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_alerta_equipamento FOREIGN KEY (equipamento_id) REFERENCES equipamentos(id)
);

-- Tabela de Metas de Eficiência
CREATE TABLE metas_eficiencia (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id NUMBER NOT NULL,
    descricao VARCHAR2(500) NOT NULL,
    tipo_meta VARCHAR2(50) NOT NULL,
    valor_alvo NUMBER(10,2) NOT NULL,
    valor_atual NUMBER(10,2) DEFAULT 0,
    unidade VARCHAR2(20),
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    status VARCHAR2(20) DEFAULT 'EM_ANDAMENTO',
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_meta_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id)
);

-- Tabela de Relatórios de Sustentabilidade
CREATE TABLE relatorios_sustentabilidade (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id NUMBER NOT NULL,
    periodo VARCHAR2(50) NOT NULL,
    consumo_total_kwh NUMBER(10,2),
    custo_total NUMBER(10,2),
    economia_kwh NUMBER(10,2),
    reducao_co2_kg NUMBER(10,2),
    eficiencia_percentual NUMBER(5,2),
    observacoes CLOB,
    data_geracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_relatorio_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id)
);

-- Índices para melhorar performance
CREATE INDEX idx_consumo_data ON consumo_energia(data_leitura);
CREATE INDEX idx_consumo_empresa ON consumo_energia(empresa_id);
CREATE INDEX idx_alerta_empresa ON alertas(empresa_id);
CREATE INDEX idx_alerta_status ON alertas(status);
CREATE INDEX idx_equipamento_empresa ON equipamentos(empresa_id);
CREATE INDEX idx_meta_empresa ON metas_eficiencia(empresa_id);
